#!/usr/bin/perl

use strict;
use warnings;
use Fcntl qw(:seek);

open(my $outfh, '>', shift(@ARGV));

while(@ARGV) {
    my($src, $bin) = splice(@ARGV, 0, 2);
    open(my $srcfh, '<', $src);
    (my $org = <$srcfh>) =~ s/^.* |\s*$//g;
    close($srcfh);
    $org = eval $org;
    seek($outfh, $org, SEEK_SET);
    open(my $binfh, '<', $bin);
    print $outfh (<$binfh>);
    close($binfh);
}
